// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: internal/models/activity.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Activity_ActivityType int32

const (
	Activity_PLAY  Activity_ActivityType = 0
	Activity_SLEEP Activity_ActivityType = 1
	Activity_EAT   Activity_ActivityType = 2
	Activity_READ  Activity_ActivityType = 3
)

// Enum value maps for Activity_ActivityType.
var (
	Activity_ActivityType_name = map[int32]string{
		0: "PLAY",
		1: "SLEEP",
		2: "EAT",
		3: "READ",
	}
	Activity_ActivityType_value = map[string]int32{
		"PLAY":  0,
		"SLEEP": 1,
		"EAT":   2,
		"READ":  3,
	}
)

func (x Activity_ActivityType) Enum() *Activity_ActivityType {
	p := new(Activity_ActivityType)
	*p = x
	return p
}

func (x Activity_ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity_ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_models_activity_proto_enumTypes[0].Descriptor()
}

func (Activity_ActivityType) Type() protoreflect.EnumType {
	return &file_internal_models_activity_proto_enumTypes[0]
}

func (x Activity_ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity_ActivityType.Descriptor instead.
func (Activity_ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_internal_models_activity_proto_rawDescGZIP(), []int{0, 0}
}

type Activity_Status int32

const (
	Activity_CREATED     Activity_Status = 0
	Activity_IN_PROGRESS Activity_Status = 1
	Activity_DONE        Activity_Status = 2
)

// Enum value maps for Activity_Status.
var (
	Activity_Status_name = map[int32]string{
		0: "CREATED",
		1: "IN_PROGRESS",
		2: "DONE",
	}
	Activity_Status_value = map[string]int32{
		"CREATED":     0,
		"IN_PROGRESS": 1,
		"DONE":        2,
	}
)

func (x Activity_Status) Enum() *Activity_Status {
	p := new(Activity_Status)
	*p = x
	return p
}

func (x Activity_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_models_activity_proto_enumTypes[1].Descriptor()
}

func (Activity_Status) Type() protoreflect.EnumType {
	return &file_internal_models_activity_proto_enumTypes[1]
}

func (x Activity_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity_Status.Descriptor instead.
func (Activity_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_models_activity_proto_rawDescGZIP(), []int{0, 1}
}

type Activity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id           int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key" gorm:"primary_key"` // Unique ID number for this person.
	Status       Activity_Status       `protobuf:"varint,3,opt,name=status,proto3,enum=model.Activity_Status" json:"status,omitempty"`
	ActivityType Activity_ActivityType `protobuf:"varint,4,opt,name=activity_type,json=activityType,proto3,enum=model.Activity_ActivityType" json:"activity_type,omitempty"`
	StartedAt    int64                 `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt   int64                 `protobuf:"varint,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
}

func (x *Activity) Reset() {
	*x = Activity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_models_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_models_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_internal_models_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Activity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Activity) GetStatus() Activity_Status {
	if x != nil {
		return x.Status
	}
	return Activity_CREATED
}

func (x *Activity) GetActivityType() Activity_ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return Activity_PLAY
}

func (x *Activity) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Activity) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

var File_internal_models_activity_proto protoreflect.FileDescriptor

var file_internal_models_activity_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xd0, 0x02, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x41, 0x0a,
	0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x36, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c, 0x41, 0x59, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x4c,
	0x45, 0x45, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x41, 0x54, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x03, 0x22, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6e, 0x6b, 0x6b, 0x61, 0x74,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_models_activity_proto_rawDescOnce sync.Once
	file_internal_models_activity_proto_rawDescData = file_internal_models_activity_proto_rawDesc
)

func file_internal_models_activity_proto_rawDescGZIP() []byte {
	file_internal_models_activity_proto_rawDescOnce.Do(func() {
		file_internal_models_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_models_activity_proto_rawDescData)
	})
	return file_internal_models_activity_proto_rawDescData
}

var file_internal_models_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_models_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_models_activity_proto_goTypes = []interface{}{
	(Activity_ActivityType)(0), // 0: model.Activity.ActivityType
	(Activity_Status)(0),       // 1: model.Activity.Status
	(*Activity)(nil),           // 2: model.Activity
}
var file_internal_models_activity_proto_depIdxs = []int32{
	1, // 0: model.Activity.status:type_name -> model.Activity.Status
	0, // 1: model.Activity.activity_type:type_name -> model.Activity.ActivityType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_models_activity_proto_init() }
func file_internal_models_activity_proto_init() {
	if File_internal_models_activity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_models_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Activity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_models_activity_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_models_activity_proto_goTypes,
		DependencyIndexes: file_internal_models_activity_proto_depIdxs,
		EnumInfos:         file_internal_models_activity_proto_enumTypes,
		MessageInfos:      file_internal_models_activity_proto_msgTypes,
	}.Build()
	File_internal_models_activity_proto = out.File
	file_internal_models_activity_proto_rawDesc = nil
	file_internal_models_activity_proto_goTypes = nil
	file_internal_models_activity_proto_depIdxs = nil
}
